sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F
from sim.models import Tmahasiswa, Tpengaduan
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image


vmahasiswa = Blueprint('vmahasiswa', __name__)


@vmahasiswa.route("/")
def home():
    return render_template("home.html")


@vmahasiswa.route("/about")
def about():
    return render_template("about.html")


@vmahasiswa.route("/data_mahasiswa", methods=['GET', 'POST'])
def data_m():
    form = mahasiswa_F()
    if form.validate_on_submit():
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa = Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data,password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun- {form.npm.data} berhasil daftar', 'primary')
        return redirect(url_for('vmahasiswa.login_mahasiswa'))
    return render_template("data-mahasiswa.html", form=form)

@vmahasiswa.route("/login_mahasiswa", methods=['GET', 'POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('vmahasiswa.home'))
    form = loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm = Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('SELAMAT DATANG KEMBALI', 'warning')
            return redirect(url_for('vmahasiswa.akunmahasiswa'))
        else:
            flash('LOGIN GAGAL, PERIKSA NPM DAN PASSWORD KEMBALI!!', 'warning')
    return render_template("login_mahasiswa.html", form=form)


@vmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template('akunmahasiswa.html')


@vmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('vmahasiswa.home'))

#simpan foto
def simpan_foto(form_foto):
    random_hex=secrets.token_hex(8)
    f_name, f_ext=os.path.splitext(form_foto.filename)
    foto_fn=random_hex + f_ext
    foto_path=os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn


@vmahasiswa.route("/edit_mahasiswa", methods=['GET', 'POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto=file_foto
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data Berhasil di Ubah', 'warning')
        return redirect(url_for('vmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.npm.data=current_user.npm
        form.nama.data=current_user.nama
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
    return render_template('edit_mahasiswa.html', form=form)


@vmahasiswa.route("/pengaduan", methods=['GET', 'POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pengaduan = Tpengaduan(subjek=form.subjek.data, katagori=form.katagori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data Berhasil di Tambahkan', 'warning')
        return redirect(url_for('vmahasiswa.pengaduan'))
    return render_template('pengaduan.html', form=form, dt_pengaduan=dt_pengaduan)


@vmahasiswa.route("/editpengaduan", methods=['GET','POST'])
def editpengaduan():
    if request.method == 'POST':
        my_data=Tpengaduan.query.get(request.form.get('id'))
        my_data.subjek=request.form['subjek']
        my_data.katagori=request.form['katagori']
        my_data.detail_pengaduan=request.form['detail_pengaduan']
        db.session.commit()
        flash('Data berhasil diubah', 'warning')
        return redirect(url_for('vmahasiswa.pengaduan'))

@vmahasiswa.route("/delete/<id>", methods=['GET', 'POST'])
def delete(id):
        my_data=Tpengaduan.query.get(id)
        db.session.delete(my_data)
        db.session.commit()
        flash('Data Anda Berhasil di Hapus', 'warning')
        return redirect(url_for('vmahasiswa.pengaduan'))

@vmahasiswa.route("/artikel/<info>")
def artikel_info(info):
    return "halaman artikel " + info

sim/templates/about.html
{% extends "base.html" %}
{% block content %}

<h1>About Me</h1>
<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aspernatur, quae. Nisi aliquam sit quia natus minima,
    consequuntur officiis sunt aliquid nihil nam? Nisi qui fuga ullam quasi quo harum magnam.</p>
<br>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis et aspernatur animi, vero possimus fugiat
    suscipit fuga modi! Earum, illum!</p>


{% endblock content %}

sim/templates/akunmahasiswa.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1 class="display-4">Hello, {{current_user.nama}}!</h1>
    <p class="lead">Selamat Datang di Sistem Informasi Pengaduan. Semoga Segala Pengaduan Anda Menjadi Perbaikan Kami.
    </p>
    <hr class="my-4">
    <p>Klik untuk memulai pengaduan anda.</p>
    <a class="btn btn-warning btn-lg" href="{{url_for ('vmahasiswa.pengaduan')}}" role="button">Pengaduan</a>
</div>


{% endblock content %}

sim/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for ('static', filename='css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

  <title>WELCOME</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for ('vmahasiswa.home')}}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for ('vmahasiswa.about')}}">About</a>
          </li>
          {%if current_user.is_authenticated%}

          {%else%}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for ('vmahasiswa.login_mahasiswa')}}">Login Mahasiswa</a>
          </li>
          {%endif%}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <div class="container mt-4 ">
    <div class="row">
      <div class="col-md-8">
        <div class="shadow p-3 mb-5 bg-white rounded">

          <!--flash-->
          {% with messages= get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, massage in messages %}

          <div class="alert alert-{{category}}">
            {{massage}}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}

          {% block content %}

          {% endblock %}

        </div>
      </div>

      <div class="col-md-4">
        <div class="shadow p-3 mb-5 bg-white rounded">
          {%if current_user.is_authenticated%}
          <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename='img/' + current_user.foto)}}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">{{current_user.nama}}</h5>
              <p class="card-text">{{current_user.email}}</p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><a href="{{ url_for ('vmahasiswa.akunmahasiswa')}}">Dasboard</a>
              </li>
              <li class="list-group-item"><a href="{{ url_for ('vmahasiswa.pengaduan')}}">Pengaduan</a>
              </li>
              <li class="list-group-item">Vestibulum at eros</li>
            </ul>
            <div class="card-body">
              <a href="{{ url_for ('vmahasiswa.editmahasiswa')}}" class="card-link">Update Data</a>
              <a href="{{ url_for ('vmahasiswa.logout_mahasiswa')}}" class="card-link">logout</a>
            </div>
          </div>
          {%else%}
          <li>Data Mahasiswa</li>
          <li>Data Dosen</li>
          {%endif%}

        </div>
      </div>

    </div>

  </div>
  </div>
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

</html>

sim/templates/data-mahasiswa.html
{% extends "base.html" %}
{% block content %}
<h1>Daftar Akun</h1>
<form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
                {{form.npm.label(class="form-control-label")}}
                {% if form.npm.errors %}
                {{form.npm(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.npm.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.npm(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control")}}
        </div>

        <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                {{form.email(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.email(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.kelas.label(class="form-control-label")}}
                {{form.kelas(class="form-control")}}
        </div>

        <div class="form-group">
                {{form.alamat.label(class="form-control-label")}}
                {{form.alamat(class="form-control")}}
        </div>

        <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                {{form.password(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.password(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.konf_pass.label(class="form-control-label")}}
                {% if form.konf_pass.errors %}
                {{form.konf_pass(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.konf_pass.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.konf_pass(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
        </div>

</form>

{% endblock content %}

sim/templates/edit_mahasiswa.html
{% extends "base.html" %}
{% block content %}
<h1>Update Data Profil</h1>
<form method="POST" enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class="form-group">
                {{form.npm.label(class="form-control-label")}}
                {% if form.npm.errors %}
                {{form.npm(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.npm.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.npm(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.nama.label(class="form-control-label")}}
                {{form.nama(class="form-control")}}
        </div>

        <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                {{form.email(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.email(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.kelas.label(class="form-control-label")}}
                {{form.kelas(class="form-control")}}
        </div>

        <div class="form-group">
                {{form.alamat.label(class="form-control-label")}}
                {{form.alamat(class="form-control")}}
        </div>

        <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                {{form.password(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.password(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.konf_pass.label(class="form-control-label")}}
                {% if form.konf_pass.errors %}
                {{form.konf_pass(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.konf_pass.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.konf_pass(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.foto.label(class="form-control-label")}}
                {% if form.foto.errors %}
                {{form.foto(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.foto.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.foto(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
        </div>

</form>

{% endblock content %}

sim/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
    <h1 class="display-4">Welcome!</h1>
    <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab perspiciatis illum voluptate veniam
        tempora repellendus, quam in magnam debitis dolore dolor aut rem. Nam modi sapiente quod fugit nostrum placeat
        sed hic incidunt magnam officiis, ipsam repellendus laboriosam maxime provident exercitationem, dolorum amet
        sint debitis error eveniet et sequi. Corrupti est recusandae fuga. Asperiores et provident quisquam eum
        deleniti, culpa voluptatum voluptatibus pariatur accusamus officiis minima perferendis eius voluptatem. Unde
        mollitia dicta omnis in labore voluptatum error magni, sint facilis, aliquid quidem distinctio tenetur totam
        tempora id ut animi nobis nesciunt molestiae consectetur minima fugiat nulla? Eligendi obcaecati modi vel?</p>
    <hr class="my-4">
</div>


{% endblock content %}

sim/templates/login_mahasiswa.html
{% extends "base.html" %}
{% block content %}
<h1>Login Mahasiswa</h1>
<form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
                {{form.npm.label(class="form-control-label")}}
                {% if form.npm.errors %}
                {{form.npm(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.npm.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.npm(class="form-control")}}
                {% endif %}
        </div>


        <div class="form-group">
                {{form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                {{form.password(class="form-control is-invalid")}}

                <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{error}}</span>
                        {% endfor %}
                </div>
                {% else %}
                {{form.password(class="form-control")}}
                {% endif %}
        </div>

        <div class="form-group">
                {{form.submit(class="btn btn-primary")}}
        </div>

        <span><a href="{{ url_for ('vmahasiswa.data_m')}}">Daftar Akun</a></span>

</form>

{% endblock content %}

sim/templates/pengaduan.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <h3>Pengaduan</h3>
  <hr class="my-4">

  <!--form pengaduan-->
  <form method="POST">
    {{form.hidden_tag()}}

    <div class="form-group">
      {{form.subjek.label(class="form-control-label")}}
      {% if form.subjek.errors %}
      {{form.subjek(class="form-control is-invalid")}}

      <div class="invalid-feedback">
        {% for error in form.subjek.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.subjek(class="form-control")}}
      {% endif %}
    </div>

    <div class="form-group">
      {{form.katagori.label(class="form-control-label")}}
      {% if form.katagori.errors %}
      {{form.kategori(class="form-control is-invalid")}}

      <div class="invalid-feedback">
        {% for error in form.katagori.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.katagori(class="form-control")}}
      {% endif %}
    </div>

    <div class="form-group">
      {{form.detail_pengaduan.label(class="form-control-label")}}
      {% if form.detail_pengaduan.errors %}
      {{form.detail_pengaduan(class="form-control is-invalid")}}

      <div class="invalid-feedback">
        {% for error in form.detail_pengaduan.errors %}
        <span>{{error}}</span>
        {% endfor %}
      </div>
      {% else %}
      {{form.detail_pengaduan(class="form-control")}}
      {% endif %}
    </div>

    <div class="form-group">
      {{form.submit(class="btn btn-primary")}}
    </div>

  </form>
  <hr class="my-4">
  <h5>Data Pengaduan</h5>

  <table class="table table-responsive table-hover table-warning">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Tgl</th>
        <th scope="col">Subjek</th>
        <th scope="col">Katagori</th>
        <th scope="col">Detail Pengaduan</th>
        <th scope="col">Id Mahasiswa</th>
        <th scope="col">Edit</th>
        <th scope="col">Hapus</th>
      </tr>
    </thead>

    <tbody>
      {% for data in dt_pengaduan%}
      <tr>
        <td scope="row"><a href="{{data.id}}" data-toggle="modal" data-target="#modalDetail{{data.id}}">O</a></td>
        <td>{{data.tgl_post}}</td>
        <td>{{data.subjek}}</td>
        <td>{{data.katagori}}</td>
        <td>{{data.detail_pengaduan}}</td>
        <td>{{data.mahasiswa_id}} / {{data.mahasiswa.nama}}</td>
        <td>
          <a href="{{'editpengaduan'}}/{{data.id}}" class="btn btn-warning btn-xs" data-toggle="modal"
            data-target="#modaledit{{data.id}}">Edit</a>
        </td>
        <td>
          <a href="{{'delete'}}/{{data.id}}" class="btn btn-danger btn-xs"
            onclick="return confirmn('Apakah Kamu Akan Menghapus Data?')">Hapus</a>
        </td>

      </tr>

      <!--edit data pengaduan-->

      <div id="modalEdit{{data.id}}" class="modal fade " role="dialog">
        <div class="modal-dialog">

          <!-- modal konten -->
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Edit Data</h4>
            </div>

            <div class="modal-body">
              <form action="{{url_for('vmahasiswa.editpengaduan')}}" method="POST">

                <div class="form-group">
                  <label>Subjek:</label>
                  <input type="hidden" name="id" value="{{data.id}}">
                  <input type="text" class="form-control" name="subjek" value="{{data.subjek}}">
                </div>

                <div class="form-group">
                  <label>Katagori:</label>
                  <input type="text" class="form-control" name="katagori" value="{{data.katagori}}">
                </div>

                <div class="form-group">
                  <label>Detail Pengaduan:</label>
                  <input type="text" class="form-control" name="detail_pengaduan" value="{{data.detail_pengaduan}}">
                </div>

                <div class="form-group">
                  <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
              </form>
              <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </tbody>

    <!-- awal detail pengaduan -->
    <div id="modalDetail{{data.id}}" class="modal fade " role="dialog">
      <div class="modal-dialog">

        <!-- modal konten -->
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Detail Data Mahasiswa</h4>
          </div>

          <div class="modal-body">
            <div class="row">

              <div class="col-md-4">
                <div class="form-group">
                  <label>Npm</label>
                </div>
                <div class="form-group">
                  <label>Nama</label>
                </div>
                <div class="form-group">
                  <label>Kelas</label>
                </div>
                <div class="form-group">
                  <label>Alamat</label>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label>: {{data.mahasiswa.npm}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.mahasiswa.nama}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.mahasiswa.kelas}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.mahasiswa.alamat}}</label>
                </div>
              </div>
            </div>
          </div>

          <div class="modal-header">
            <h4>Detail Data Pengaduan</h4>
          </div>

          <div class="modal-body">
            <div class="row">

              <div class="col-md-6">
                <div class="form-group">
                  <label>Subjek</label>
                </div>
                <div class="form-group">
                  <label>Katagori</label>
                </div>
                <div class="form-group">
                  <label>Detail Pengaduan</label>
                </div>
                <div class="form-group">
                  <label>Tgl Post</label>
                </div>
                <div class="form-group">
                  <label>Id Mahasiswa</label>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label>: {{data.subjek}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.katagori}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.detail_pengaduan}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.tgl_post}}</label>
                </div>
                <div class="form-group">
                  <label>: {{data.mahasiswa_id}}</label>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
</div>
</div>

<!-- akhir detail pengaduan -->
{%endfor%}

</table>

</div>

{% endblock content %}